services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: irielle-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword
      MONGO_INITDB_DATABASE: irielle
    volumes:
      - mongodb_data:/data/db
      - ./clair-app/docker/mongo-init.js:/docker-entrypoint-initdb.d/01-mongo-init.js:ro
      - ./clair-app/docker/seed-data.js:/docker-entrypoint-initdb.d/02-seed-data.js:ro
    networks:
      - irielle-network

  # ChromaDB for Vector Storage
  chromadb:
    image: chromadb/chroma:latest
    container_name: irielle-chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    networks:
      - irielle-network

  # Ollama AI Service with Model Management
  ollama:
    build:
      context: ./clair-app/docker
      dockerfile: ollama-models.dockerfile
    container_name: irielle-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - irielle-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0

  # Python FastAPI Backend for AI
  ai-backend:
    build:
      context: ./clair-app/ai-backend
      dockerfile: Dockerfile
    container_name: irielle-ai-backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URL=mongodb://admin:securepassword@mongodb:27017/irielle?authSource=admin
      - CHROMA_URL=http://chromadb:8000
      - OLLAMA_HOST=ollama:11434
    depends_on:
      - mongodb
      - chromadb
      - ollama
    networks:
      - irielle-network

  # CLAIR Next.js Frontend Application
  clair-frontend:
    build:
      context: ./clair-app
      dockerfile: Dockerfile
    container_name: irielle-clair-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - mongodb
      - ai-backend
    networks:
      - irielle-network


  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: irielle-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./clair-app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./clair-app/nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - clair-frontend
    networks:
      - irielle-network

  # Certbot for Let's Encrypt SSL
  certbot:
    image: certbot/certbot
    container_name: irielle-certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - nginx

  # SSL Setup Service
  ssl-setup:
    build:
      context: ./clair-app/scripts
      dockerfile: Dockerfile.ssl-setup
    container_name: irielle-ssl-setup
    volumes:
      - ./clair-app/nginx/conf.d:/nginx/conf.d
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOMAIN=dev.meziani.org
      - EMAIL=support@meziani.org
    depends_on:
      - nginx
    profiles:
      - ssl-setup

volumes:
  mongodb_data:
  chromadb_data:
  ollama_data:
  certbot_data:
  certbot_www:

networks:
  irielle-network:
    driver: bridge