FROM alpine:latest

RUN apk add --no-cache \
    bash \
    curl \
    docker-cli \
    certbot

COPY ssl-setup.sh /usr/local/bin/ssl-setup.sh
RUN chmod +x /usr/local/bin/ssl-setup.sh

WORKDIR /app

ENTRYPOINT ["/usr/local/bin/ssl-setup.sh"]