name: SSL Certificate Renewal

on:
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  renew-ssl:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - name: Renew SSL certificates
      run: |
        echo "🔐 Checking SSL certificate renewal..."
        
        # Check if certificates exist and are close to expiry
        if docker run --rm -v clair_certbot_data:/etc/letsencrypt certbot/certbot certificates | grep -q "dev.meziani.org"; then
          echo "📋 Current certificate status:"
          docker run --rm -v clair_certbot_data:/etc/letsencrypt certbot/certbot certificates
          
          # Attempt renewal (certbot only renews if needed)
          echo "🔄 Attempting certificate renewal for dev.meziani.org..."
          docker run --rm -v clair_certbot_data:/etc/letsencrypt -v clair_certbot_www:/var/www/certbot certbot/certbot renew --webroot --webroot-path=/var/www/certbot --quiet
          
          # Check if renewal was successful
          if [ $? -eq 0 ]; then
            echo "✅ Certificate renewal check completed successfully"
            
            # Reload nginx to use new certificates
            echo "🔄 Reloading nginx to use updated certificates..."
            docker-compose exec nginx nginx -s reload || docker-compose restart nginx
            
            echo "🎉 SSL certificate renewal completed successfully!"
          else
            echo "⚠️  Certificate renewal failed or not needed"
          fi
        else
          echo "⚠️  No SSL certificates found for dev.meziani.org"
          echo "Use the main deployment workflow to generate initial certificates"
        fi